name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua
      uses: leafo/gh-actions-lua@v8.0.0
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "luajit-2.0.5"
          - "luajit-openresty"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.lua-version }}
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4
    -
      name: Install Required Packages
      run: |
        sudo apt install lcov -y
        sudo apt install libtool
        wget https://causal.agency/libretls/libretls-3.5.2.tar.gz
        tar xvzf ./libretls-3.5.2.tar.gz
        cd ./libretls-3.5.2
        autoreconf -fi
        ./configure
        make all
        sudo make install
    -
      name: Install
      run: |
        luarocks make LIBTLS_DIR=/usr/local LIBTLS_COVERAGE=1
    -
      name: Install Test Tools
      run: |
        luarocks install testcase
        luarocks install exec
        luarocks install io-fileno
    -
      name: Run Test
      run: |
        testcase ./test/
    # -
    #   name: Generate coverage reports
    #   run: |
    #     sh ./covgen.sh
    # -
    #   name: Upload c coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     files: ./coverage/lcov.info
    #     flags: unittests
